# Generated by Django 2.1 on 2018-08-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20180817_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartManager',
        ),
    ]
